FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/store-service ./cmd/store-service

FROM alpine:3.20 AS runtime

WORKDIR /app

COPY --from=build /bin/store-service /app/store-service

RUN mkdir -p /app/uploads

EXPOSE 8005

CMD ["/app/store-service"]
