package domain

func DefaultSettings() map[string]DefaultSetting {
	settings := []DefaultSetting{
		{
			Key:         "sale.auto_print",
			Value:       true,
			GroupName:   "sale",
			DataType:    "boolean",
			Description: "Tu dong in hoa don",
			IsPublic:    true,
		},
		{
			Key:         "sale.allow_negative_stock",
			Value:       false,
			GroupName:   "sale",
			DataType:    "boolean",
			Description: "Cho phep ban am kho",
			IsPublic:    true,
		},
		{
			Key:         "sale.allow_edit_price",
			Value:       false,
			GroupName:   "sale",
			DataType:    "boolean",
			Description: "Cho phep sua gia khi ban",
			IsPublic:    true,
		},
		{
			Key:         "sale.default_payment_method",
			Value:       "cash",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Phuong thuc thanh toan mac dinh",
			IsPublic:    true,
		},
		{
			Key:         "sale.bank_account_no",
			Value:       "",
			GroupName:   "sale",
			DataType:    "string",
			Description: "So tai khoan nhan tien QR",
			IsPublic:    true,
		},
		{
			Key:         "sale.bank_account_name",
			Value:       "",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Ten tai khoan nhan tien QR",
			IsPublic:    true,
		},
		{
			Key:         "sale.bank_acq_id",
			Value:       "",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Ma BIN ngan hang nhan QR",
			IsPublic:    true,
		},
		{
			Key:         "sale.bank_qr_add_info_mode",
			Value:       "order_code",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Noi dung chuyen khoan QR (order_code/custom)",
			IsPublic:    true,
		},
		{
			Key:         "sale.bank_qr_add_info_custom",
			Value:       "",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Noi dung chuyen khoan QR tuy chinh",
			IsPublic:    true,
		},
		{
			Key:         "sale.customer_display_show_price",
			Value:       true,
			GroupName:   "sale",
			DataType:    "boolean",
			Description: "Man hinh khach hien gia tung dong",
			IsPublic:    true,
		},
		{
			Key:         "sale.customer_display_show_total",
			Value:       true,
			GroupName:   "sale",
			DataType:    "boolean",
			Description: "Man hinh khach hien tong tien",
			IsPublic:    true,
		},
		{
			Key:         "sale.customer_display_ads",
			Value:       []string{},
			GroupName:   "sale",
			DataType:    "json",
			Description: "Danh sach anh quang cao man hinh khach",
			IsPublic:    true,
		},
		{
			Key:         "sale.customer_display_ads_interval_seconds",
			Value:       8,
			GroupName:   "sale",
			DataType:    "number",
			Description: "Chu ky chuyen anh quang cao (giay)",
			IsPublic:    true,
		},
		{
			Key:         "sale.customer_display_ads_transition",
			Value:       "fade",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Hieu ung chuyen ads (none/fade/slide)",
			IsPublic:    true,
		},
		{
			Key:         "sale.customer_display_ads_transition_ms",
			Value:       650,
			GroupName:   "sale",
			DataType:    "number",
			Description: "Thoi gian hieu ung ads (ms)",
			IsPublic:    true,
		},
		{
			Key:         "sale.enforce_lot_policy",
			Value:       true,
			GroupName:   "sale",
			DataType:    "boolean",
			Description: "Ban hang theo lo (ap dung FIFO/FEFO khi tao hoa don)",
			IsPublic:    true,
		},
		{
			Key:         "sale.invoice_prefix",
			Value:       "HD",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Prefix ma hoa don",
			IsPublic:    true,
		},
		{
			Key:         "sale.return_window_value",
			Value:       7,
			GroupName:   "sale",
			DataType:    "number",
			Description: "Thoi gian doi tra",
			IsPublic:    true,
		},
		{
			Key:         "sale.return_window_unit",
			Value:       "day",
			GroupName:   "sale",
			DataType:    "string",
			Description: "Don vi thoi gian doi tra (day/hour)",
			IsPublic:    true,
		},
		{
			Key:         "inventory.low_stock_threshold",
			Value:       10,
			GroupName:   "inventory",
			DataType:    "number",
			Description: "Nguong canh bao sap het hang",
			IsPublic:    true,
		},
		{
			Key:         "inventory.expiry_warning_days",
			Value:       30,
			GroupName:   "inventory",
			DataType:    "number",
			Description: "Canh bao truoc han su dung (ngay)",
			IsPublic:    true,
		},
		{
			Key:         "inventory.near_date_days",
			Value:       90,
			GroupName:   "inventory",
			DataType:    "number",
			Description: "Nguong can date (ngay)",
			IsPublic:    true,
		},
		{
			Key:         "inventory.enable_fefo",
			Value:       true,
			GroupName:   "inventory",
			DataType:    "boolean",
			Description: "Bat FEFO",
			IsPublic:    true,
		},
		{
			Key:         "inventory.fefo_threshold_days",
			Value:       180,
			GroupName:   "inventory",
			DataType:    "number",
			Description: "Nguong FEFO (ngay)",
			IsPublic:    true,
		},
		{
			Key:         "inventory.receipt_prefix",
			Value:       "PN",
			GroupName:   "inventory",
			DataType:    "string",
			Description: "Prefix phieu nhap",
			IsPublic:    true,
		},
		{
			Key:         "customer.enable_points",
			Value:       true,
			GroupName:   "customer",
			DataType:    "boolean",
			Description: "Bat tich diem",
			IsPublic:    true,
		},
		{
			Key:         "customer.points_per_amount",
			Value:       1000,
			GroupName:   "customer",
			DataType:    "number",
			Description: "So tien = 1 diem",
			IsPublic:    true,
		},
		{
			Key:         "customer.point_value",
			Value:       1000,
			GroupName:   "customer",
			DataType:    "number",
			Description: "1 diem = X dong",
			IsPublic:    true,
		},
		{
			Key:         "customer.points_expiry_months",
			Value:       12,
			GroupName:   "customer",
			DataType:    "number",
			Description: "Diem het han sau X thang",
			IsPublic:    true,
		},
		{
			Key:         "customer.tier_bronze",
			Value:       0,
			GroupName:   "customer",
			DataType:    "number",
			Description: "Moc hang Dong",
			IsPublic:    true,
		},
		{
			Key:         "customer.tier_silver",
			Value:       1000,
			GroupName:   "customer",
			DataType:    "number",
			Description: "Moc hang Bac",
			IsPublic:    true,
		},
		{
			Key:         "customer.tier_gold",
			Value:       5000,
			GroupName:   "customer",
			DataType:    "number",
			Description: "Moc hang Vang",
			IsPublic:    true,
		},
		{
			Key:         "customer.tier_diamond",
			Value:       20000,
			GroupName:   "customer",
			DataType:    "number",
			Description: "Moc hang Kim cuong",
			IsPublic:    true,
		},
		{
			Key:         "promotion.auto_hide_expired",
			Value:       true,
			GroupName:   "promotion",
			DataType:    "boolean",
			Description: "Tu dong an khuyen mai het han",
			IsPublic:    true,
		},
		{
			Key:         "promotion.auto_delete_days",
			Value:       30,
			GroupName:   "promotion",
			DataType:    "number",
			Description: "Xoa khuyen mai sau X ngay het han",
			IsPublic:    true,
		},
		{
			Key:         "backup.auto_enabled",
			Value:       false,
			GroupName:   "backup",
			DataType:    "boolean",
			Description: "Bat sao luu tu dong",
			IsPublic:    false,
		},
		{
			Key:         "backup.auto_interval_hours",
			Value:       24,
			GroupName:   "backup",
			DataType:    "number",
			Description: "Chu ky sao luu tu dong (gio)",
			IsPublic:    false,
		},
		{
			Key:         "backup.max_files",
			Value:       10,
			GroupName:   "backup",
			DataType:    "number",
			Description: "So ban sao luu toi da",
			IsPublic:    false,
		},
		{
			Key:         "backup.sync_server_url",
			Value:       "",
			GroupName:   "backup",
			DataType:    "string",
			Description: "URL server dong bo",
			IsPublic:    false,
		},
		{
			Key:         "backup.sync_api_key",
			Value:       "",
			GroupName:   "backup",
			DataType:    "string",
			Description: "API key dong bo",
			IsPublic:    false,
		},
		{
			Key:         "system.timezone",
			Value:       "Asia/Ho_Chi_Minh",
			GroupName:   "system",
			DataType:    "string",
			Description: "Mui gio he thong",
			IsPublic:    true,
		},
		{
			Key:         "system.currency",
			Value:       "VND",
			GroupName:   "system",
			DataType:    "string",
			Description: "Don vi tien te",
			IsPublic:    true,
		},
		{
			Key:         "system.date_format",
			Value:       "DD/MM/YYYY",
			GroupName:   "system",
			DataType:    "string",
			Description: "Dinh dang ngay",
			IsPublic:    true,
		},
	}

	result := make(map[string]DefaultSetting, len(settings))
	for _, item := range settings {
		result[item.Key] = item
	}

	return result
}
