FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/payment-qr-service ./main.go

FROM alpine:3.20 AS runtime

WORKDIR /app

COPY --from=build /bin/payment-qr-service /app/payment-qr-service

EXPOSE 8008

CMD ["/app/payment-qr-service"]
